const serviceList: string[] = [
    'Clean Up - Basic',
    'Quick Glow Mask - Basic',
    'D-Tan - Basic',
    ' Mini Facial',
    'Instant Glow Facial',
    ' Hydrating Facial',
    'Skin Lightning Facial',
    '24K Gold Facial',
    'Anti Aging Facial',
    'Signture Facial',
    'Eye Brow - Threading',
    'Upper Lip - Threading',
    'Chin - Threading',
    'ForeHead - Threading',
    'Side Lock - Threading',
    'Full Neck - Threading',
    'Neck - Threading',
    'Full Arms - Normal Waxing',
    'Full Legs - Normal Waxing',
    'Half Arms - Normal Waxing',
    'Half Legs - Normal Waxing',
    'Full Back - Normal Waxing',
    'Full Front - Normal Waxing',
    'Full Body - Normal Waxing',
    'Under Arms - Normal Waxing',
    'Full Arms - Rica Waxing',
    'Full Legs - Rica Waxing',
    'Half Arms - Rica Waxing',
    'Half Legs - Rica Waxing',
    'Full Back - Rica Waxing',
    'Full Front - Rica Waxing',
    ' Full Body - Rica Waxing',
    'Under Arms - Rica Waxing',
    '  Upper Lip - Brazilian Waxing',
    'Chin/Chicks - Brazilian Waxing',
    'Side Lock - Brazilian Waxing',
    'Full Face - Brazilian Waxing',
    'Under Arms - Brazilian Waxing',
    'Neck - Brazilian Waxing',
    'Bikini Line - Brazilian Waxing',
    'Full Bikini - Brazilian Waxing',
    ' Full Arms - Fairness for women',
    'Full Legs - Fairness for women',
    'Half Arms - Fairness for women',
    'Half Legs - Fairness for women',
    ' Full Back - Fairness for women',
    'Full Front - Fairness for women',
    'Blouse Line - Fairness for women',
    ' Under Arms - Fairness for women',
    'Full Body - Fairness for women',
    'Classic Manicure',
    'Classic Pedicure',
    'Anti Aging Manicure',
    'Anti Aging Pedicure',
    '  Crystal Manicure',
    ' Crystal Pedicure',
    'Chocolate Manicure',
    'Chocolate Pedicure',
    'Aroma Manicure',
    ' Aroma Pedicure',
    'Cut - Fail with Nail Paint',
    'Creative Nail Art for Hand',
    'Nail Art',
    'Hand Paint',
    'Aroma body Massage ( 45 min )',
    '  Swedish Body Massage ( 45 min )',
    ' Deep Tissue Massage ( 45 min )',
    ' Aroma body Massage ( 60 min )',
    'Swedish Body Massage ( 60 min )',
    'Deep Tissue Massage ( 60 min )',
    'Back Massage ( 20 min )',
    ' Foot Massage ( 20 min )',
    ' Body Polish',
    'Express Make Up',
    ' Saree Draping',
    'Hair-Do',
    ' Ammoina Free Colour',
    ' Fashion Colour',
    ' Ammonia Free Colour(Root)',
    'Global Colour ( Small )',
    ' Global Colour ( Medium )',
    ' Global Colour ( Large )',
    ' Global Highlights ( Small )',
    'Global Highlights ( Medium )',
    ' Global Highlights ( Large )',
    'Per Streak',
    ' Ironing ( Small )',
    '  Ironing ( Medium )',
    '  Ironing ( Large )',
    ' Hair Straightening (Small)',
    'Hair Straightening ( Medium )',
    '  Hair Straightening ( Large )',
    ' Hair Rebounding ( Small )',
    '  Hair Rebounding ( Medium )',
    'Hair Rebounding ( Large )',
    ' Keratin Treatment ( Small )',
    ' Keratin Treatment ( Medium )',
    'Keratin Treatment ( Large )',
    '  Tong Curls ( Small )',
    ' Tong Curls ( Medium )',
    ' Tong Curls ( Large )',
    ' Hair Wash ( Small & Medium )',
    '  Hair Wash ( Large )',
    ' Blow-Dry ( Small & Medium )',
    '  Blow-Dry ( Large )',
    ' Basic Hair Cut - Women',
    '  Basic Hair Cut With Wash',
    'Triming of Style',
    '  Baby Cut',
    'Baby Cut / Styling',
    ' Baby Cut / Styling / Short Cut',
    ' Style By Director',
    ' Fringe Hair Cut',
    ' Basic Hair Cut - Men',
    ' Change of Style',
    '  Boy Hair Cut',
    '  Shaving',
    '  Beard Design',
    'Beard Trim',
    '  Head Shave',
    ' De - Stress Spa ( Small )',
    ' De - Stress Spa ( Medium )',
    'De - Stress Spa ( Large )',
    ' Protein Rush Spa ( Small )',
    ' Protein Rush Spa ( Medium )',
    '  Protein Rush Spa ( Large )',
    '  De - Stress Spa - Men',
    'Protein Rush Spa - Men',
    '  Anti Dandruff - Women',
    '  Anti Hair Fall - Women',
    'Anti Dandruff - Men',
    ' Anti Hair Fall - Men',
    'Hair Oil Massage - Men',
    ' Hair Oil Massage - Women',
    '  Under Eye Treatment',
    '  Advance D-Tan',
];

export default serviceList;
